### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by BubbleBubblePlayz** [face-hh/discordmium#16]
I cant seem to insert the token with it not breaking.
```module.exports = async function browse("token", guildID, clearTime = 300000)```

**Comment by BubbleBubblePlayz** [comment]
It just throws an "Unexpected String"

**Comment by face-hh** [comment]
That is not the place you have to change it.

**Comment by BubblePlayzTHEREAL** [comment]
Where is it?

**Comment by face-hh** [comment]
> Where is it?

https://github.com/face-hh/discordmium#usage
