### ISSUE TITLE
Crash on /browse

### ISSUE THREAD

**Issue by Dominik159E0** [face-hh/discordmium#17]
![obrázok](https://user-images.githubusercontent.com/90928810/211086653-6fd0f791-7c10-404a-a854-e924ac66650f.png)

**Comment by face-hh** [comment]
Please update to the latest version and let me know if it fixes the issue. If it doesn't then you will probably have to specify the args `--no-sandbox` and specify the chrome path.

**Comment by Dominik159E0** [comment]
Somehow ir works on another machine so that's good but thank you for the help

**Comment by face-hh** [comment]
Yeah it's something with the installation of your browser.
