### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hikaoffical1** [face-hh/discordmium#4]
npm ERR! Missing script: "start"
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-12-31T16_57_51_525Z-debug-0.log
exit status 1

**Comment by Audomations** [comment]
in your ```package.json``` file put the the following json inside:

```json
"scripts": {
    "start": "index.js"
}
```

**Comment by face-hh** [comment]
Alternatively you can run `node .` instead of `npm run start`.
