### ISSUE TITLE
typing

### ISSUE THREAD

**Issue by asdfzxcvbn** [face-hh/discordmium#5]
i feel incredibly stupid opening an issue for this but here it goes: how do i even type? i've seen the youtube video where you type without any problems, but i just can't get it to work. i get the mouse in the search box, click inside it, then press the typing key and send a message. the bot reacts to my message with a checkmark, but after refreshing the screenshot by clicking another button, there is no text visible. am i just being stupid or is there an issue?

**Comment by asdfzxcvbn** [comment]
also forgot to mention that i've tried running it on both my VPS as well as my own computer, if that means anything

**Comment by face-hh** [comment]
Hello @asdfzxcvbn, thank you for reporting this issue. I will look into this and hopefully find a fix.

**Comment by face-hh** [comment]
It seems like I can not replicate your issue, are you sure the input element was focused when you pressed the type button?

![image](https://user-images.githubusercontent.com/69168154/210164590-52cca46f-3200-4e50-a251-fd8e35aa7bad.png)
![image](https://user-images.githubusercontent.com/69168154/210164603-1a9f4a0e-9186-456b-b83b-1757fb7967d3.png)

**Comment by Vinayak1857** [comment]
> i feel incredibly stupid opening an issue for this but here it goes: how do i even type? i've seen the youtube video where you type without any problems, but i just can't get it to work. i get the mouse in the search box, click inside it, then press the typing key and send a message. the bot reacts to my message with a checkmark, but after refreshing the screenshot by clicking another button, there is no text visible. am i just being stupid or is there an issue?

i am also facing the same issue

**Comment by face-hh** [comment]
Try modifying in `index.js`: `page.keyboard.type` => `page.type`.

**Comment by Vinayak1857** [comment]
> Try modifying in `index.js`: `page.keyboard.type` => `page.type`.

still the same problem

**Comment by face-hh** [comment]
What browser are you using? (If you're using Chrome, is it Google Chrome or
Chromium?)

**Comment by neverbxrn** [comment]
uhm i have the same issue

**Comment by neverbxrn** [comment]
but for me, bot doesn't even reacts with checkmark

**Comment by asdfzxcvbn** [comment]
alright, i've figured it out. the bot requires the message content intent enabled in order to work. maybe you could implement a system to NOT react to the message if this is disabled? (if this is possible, of course) a guide to making the discord bot itself might be helpful to other users as well, and i might open a pull request later to add this if i'm not busy.

**Comment by asdfzxcvbn** [comment]
for anyone else facing the issue, you can enable it on the bot page of your application at https://discord.com/developers/applications/your bots appid/bot
![image](https://user-images.githubusercontent.com/109937991/210187905-8cf59284-47b4-4b57-8231-026973084e2a.png)
